### ISSUE TITLE
Raw results issues

### ISSUE THREAD

**Issue by Lich-King000** [lizhou-cs/JointNLT#10]
Hi, thanks for your work.

Since your raw results on datasets are on your homepage, I download them for research.
But I found some issues in your raw results, which NL initializes. 
The **raw result of** the first frame of each sequence is the same as that of the first frame of **groundtruth**. That differs from how to get the result of the first frame you mentioned in your paper, which is obtained by grounding.

I hope to receive some answers about this. Thank you! @lizhou-cs

**Comment by lizhou-cs** [comment]
Hello, thank you for your attention to our work. First of all, it should be noted that for the target state of the first frame, we predicted it rather than using ground truth. You can refer to this section of the code for details. [Code Link](https://github.com/lizhou-cs/JointNLT/blob/94b338e19f7bc4a4d9646b0f0ac82321e9bddb26/lib/test/tracker/jointnlt.py#L76C1-L88C69)
```
            self.template_dict = [template_src, template_mask]
            with torch.no_grad():
                out_dict = self.network.forward_test(self.text_dict, self.template_dict, grounding_patch, None)
                scale_box = self._get_templates_and_anno(image, out_dict['pred_boxes'], image_top_coords,
                                                         self.params.grounding_size)
                # return shape: (b,4)
                scale_box = scale_box.squeeze()
            self.template_roi_feature = out_dict['roi_feature'].flatten(2)  # (B, C, H', W') -> (B, C, H'W')
            z_patch_arr, _, z_amask_arr = sample_target(image, scale_box, self.params.template_factor,
                                                        output_sz=self.params.template_size)
            self.template_img, _, _ = sample_target(image, scale_box, 1.0,
                                                    output_sz=144)
            template = self.preprocessor.process(z_patch_arr).cuda()
            self.state = scale_box.tolist()
```

As for the Raw Result being the same as GT, it is because according to the original code paradigm, the results are saved starting from the second frame, and we have not modified this part. Thank you for pointing it out, and we will make changes to this part of the code in the future.
