### ISSUE TITLE
transform

### ISSUE THREAD

**Issue by Leonhard-Euler-ai** [lizhou-cs/JointNLT#3]
Whether there is a conflict between the code and the comment, what exactly to use when training?
```
# can't use RandomHorizontalFlip it would change the pic would not fit the language description.,
transform_joint = tfm.Transform(tfm.ToGrayscale(probability=0.05), tfm.RandomHorizontalFlip(probability=0.5)) 
```

**Comment by lizhou-cs** [comment]
Sorry for the misunderstanding caused by the position of the comment. For the grounding image, we only apply the grounding transform as can be seen from the following code.
https://github.com/lizhou-cs/JointNLT/blob/977991d90100bea5d88db7a17c8ae8131a16fa1c/lib/train/base_functions.py#L111-L113
https://github.com/lizhou-cs/JointNLT/blob/977991d90100bea5d88db7a17c8ae8131a16fa1c/lib/train/data/processing.py#L440-L443

**Comment by Leonhard-Euler-ai** [comment]
Thanks!
